### ISSUE TITLE
Rename the repository or change Makefile (binary file name)

### ISSUE THREAD

**Issue by viktorbenei** [huytd/go-play#23]
The repo/package name is `go-play`, but Make creates a binary with the name `playgo`. The idiomatic approach is to use the package name as the name of the binary, because that way if you `go install` it you'll get the "properly" named binary (which is based on the package's name - right now it's `go-play`).

I think both should work, if you rename the repo GitHub is clever enough the redirect everything to the new URL (which would be https://github.com/huytd/playgo), or Makefile could be changed to generate the binary with the name `go-play` instead of `playgo`.

**Comment by huytd** [comment]
Well.. I think it's better to change the binary name in `Makefile`. Renaming repo would be complex since all the traffic now points to `go-play`, and I don't know if Github will redirect it or not. 

So, change the `Makefile` will be ok for me :D

**Comment by viktorbenei** [comment]
PR: https://github.com/huytd/go-play/pull/24

I renamed playgo to go-play everywhere, as I think any inconsistency can lead to confusion, but obviously it's up for discussion.

IMO Playgo would be a better name than go-play, but I understand if you have concerns about the URL, although our experience is that GitHub handles these repo renaming situations quite well.

**Comment by huytd** [comment]
Hey, I just made a test. Look like Github now able to automatically redirect if user changed his repo name. So we have 2 options now :D keep the `go-play` name or use `playgo` name. :D

**Comment by viktorbenei** [comment]
I guess then it's up to you to choose the "right" one ;)

**Comment by viktorbenei** [comment]
My only wish is to make it consistent :P

**Comment by huytd** [comment]
😆 haha yeah I like the "right" one

**Comment by viktorbenei** [comment]
I'll create a new PR then ;)

**Comment by viktorbenei** [comment]
Updated the PR (https://github.com/huytd/go-play/pull/24)

**Comment by huytd** [comment]
Renamed :)

**Comment by viktorbenei** [comment]
🎉😊
